# -*- mode: ruby -*-
# vi: set ft=ruby :

# Overwrite host locale in ssh session
ENV["LC_ALL"] = "en_US.UTF-8"

# Buildah host settings

dev7_hostname = "dev7.v"
dev7_ip = "192.168.60.40"
dev7_memory = 2048

local_folder = "/Users/tok/repos"
remote_mount = "/repos/"

base_box = "generic/rhel7"

Vagrant.configure("2") do |config|

  # Avoid using the Virtualbox guest additions

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.define "dev7" do |dev7|    
    dev7.vm.box = base_box
    dev7.vm.hostname = dev7_hostname
    dev7.vm.network "private_network", ip: dev7_ip
    dev7.vm.synced_folder local_folder, remote_mount
    dev7.ssh.insert_key = false
    dev7.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]

    dev7.vm.provider :virtualbox do |vb|
      vb.name = dev7_hostname
      vb.memory = dev7_memory
    end
  end

  config.vm.provision "ansible" do |ansible|
     ansible.playbook = "provision-dev7.yml"
  end
end

